### ISSUE TITLE
[BUG] In BIDS, data-type may be at subject or session level

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/NeuroBlueprint#41]
Currently NeuroBlueprint mandates the placement of data-type folders (behav, ephys, funcimg) in the session level, and histology in the subject level. We discussed a little on slack about moving histology into the session level for simplicity. However of course BIDS does not actually mandate the session level, and data-type folders can be at the subject or session level.

I think for BIDS compliance it makes sense to also support having this flexibility. However it does make data-discovery in things like `spikewrap` more difficult, and `datashuttle` will require some massaging + a lot more tests and checks (e.g. error if trying to put a data-type folder at the subject level that is already somewhere in the session level,  and vice-versa). But I think in principle it makes sense?

**Comment by adamltyson** [comment]
I think ideally users could do both, I can see microscopy only projects that could be either:
- Just one "session", i.e. a single confocal image, for which adding creating `ses-01` seems onerous
- A more complex project involving tissue clearing, imaging session 1, restaining, imaging session 2, sectioning, imaging session 3. Here sessions makes much more sense.

If this can be implemented within DataShuttle and NIU tools that ingest these data it would be great, but that could be a lot of overhead. If it's too much work, I'd be happy to prescribe what users should do.

**Comment by niksirbi** [comment]
> * A more complex project involving tissue clearing, imaging session 1, restaining, imaging session 2, sectioning, imaging session 3. Here sessions makes much more sense.

Actually, that makes sense. I was not familiar with such histology workflows. 

How about this:
- make session level optional (up to the user)
- if no session level, put all datatypes under subject (obviously)
- if session level is used, put datatypes under a session (incl. histology)
- do not mix subject-level and session-level datatypes.

**Comment by JoeZiminski** [comment]
I think this is most clear and would avoid lots of problems with parsing. Technically BIDS does [allow this](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html) however, but it is under SHOULD

```
In datasets where at least one subject has more than one session, this additional subdirectory later SHOULD be added for all subjects in the dataset. 
```

I guess this becomes a more general question, as how strictly it is feasible to align with BIDS / if we should enforce some BIDS SHOULD as MUST to make software development easiest. Some possible options:

1) Follow BIDS exactly in NeuroBlueprint but in specific tools enforce stricter behaviour (probably not good because we cannot then claim our tools work with NeuroBlueprint 
2) Have NeuroBlueprint  be more restrictive than BIDS in places (not good as then there is confusion between the specifications, and essentially they have diverged).
3) Allow full BIDS (possibly lead to hellish file / folder discovery problems).

I think all of these are bad, personally I'd be up for trying to maintain full alignment with BIDS unless there is a specific instance where it is just not possible to robustly perform file / folder search operations. I could try and handle this case in `datashuttle` and see how hard it is.

**Comment by adamltyson** [comment]
> personally I'd be up for trying to maintain full alignment with BIDS unless there is a specific instance where it is just not possible to robustly perform file / folder search operations.

I think this should be the general aim. We should align with BIDS as long as it allows us to achieve our other goals. If we need to diverge, then we should. There's a reason why we created NeuroBlueprint in the first place. Turning "real" BIDS into something that supports all of our data types is currently too much work to be feasible in the time frame we have.

**Comment by adamltyson** [comment]
Ofc I hope that NeuroBlueprint and BIDS will converge eventually

**Comment by adamltyson** [comment]
> Actually, that makes sense. I was not familiar with such histology workflows.

@niksirbi to be clear, these are rare, but it's something we would like to make possible at SWC with the mesospim etc.

**Comment by JoeZiminski** [comment]
> I think this should be the general aim. We should align with BIDS as long as it allows us to achieve our other goals. If we need to > diverge, then we should. There's a reason why we created NeuroBlueprint in the first place. Turning "real" BIDS into something > that supports all of our data types is currently too much work to be feasible in the time frame we have. 

This makes sense, if we are getting bogged down and spending a lot of time trying to maintain BIDS compatability, and making some more stringent criteria will make life much easier and the software more robust we should do it. I suggest we start with full BIDS compliance and then reduce it if issues arise with implementation.

**Comment by JoeZiminski** [comment]
updated with decision in #45
