### ISSUE TITLE
Refer to 'project' folder as 'experiment' folder?

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/NeuroBlueprint#42]
In the docs for here and datashuttle I think in the general  the root folder is referred to as the 'project' folder. Maybe this is a little ambigious, because really it is expected that it will be 1 'project' per experiment. I think it is unlikely people will merge across projects, though maybe this is not true. In general systems neuroscience experiments are so big that an experiment is basically a project. But, for example a short pilot followed by main experiment, I would (I think) imagine the pilot would be split out into a separate project. I wonder what you think?

**Comment by niksirbi** [comment]
I would favour keeping the current name. That's what BIDS uses, and besides, the definition of "experiment" can be equally ambiguous and will differ across fields/labs.

Instead, we would perhaps add a note emphasising that the users can choose what constitutes a "project" based on pragmatic needs (and maybe provide some sensible use cases / example).

**Comment by adamltyson** [comment]
I like project. Naively I think of:
* Project - the whole thing, including multiple modalities
* Experiment - something smaller. Maybe a single modality.

**Comment by JoeZiminski** [comment]
Okay this sounds good I agree, that's a nice idea to add a note, maybe if people raise questions about this on the course next week we can add this. Cheers

**Comment by adamltyson** [comment]
Is it worth starting a glossary (as discussed yesterday)?

**Comment by niksirbi** [comment]
BIDs has a [definitions](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#definitions) section as well as an extensive [glossary of schema objects](https://bids-specification.readthedocs.io/en/stable/glossary.html).

I think what we need right now is the "definitions" part.

The animal electrophysiology BEP also defines [some basic terms here](https://docs.google.com/document/d/1oG-C8T-dWPqfVzL2W8HO3elWK8NIh2cOCPssRGv23n0/edit#heading=h.1fob9te).
